BEGIN_FACTORY(app_simple_notify_drawing) 
FACTORY_DEPENDENCY(draw2d_cairo) 
FACTORY_DEPENDENCY(experience_core) 
FACTORY_DEPENDENCY(imaging_freeimage) 
FACTORY_DEPENDENCY(node_linux) 
FACTORY_DEPENDENCY(windowing_x11) 
FACTORY_DEPENDENCY(app_simple_notify_drawing) 
END_FACTORY() 
