BEGIN_FACTORY(app_simple_application) 
FACTORY_DEPENDENCY(draw2d_quartz2d) 
FACTORY_DEPENDENCY(experience_core) 
FACTORY_DEPENDENCY(node_macos) 
FACTORY_DEPENDENCY(windowing_macos) 
FACTORY_DEPENDENCY(write_text_quartz2d) 
FACTORY_DEPENDENCY(app_simple_application) 
END_FACTORY() 
